apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
stringData:
  secret: {{ .Values.secret }}

---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
type: Opaque
stringData:
  username: {{ .Values.mongodb.username }}
  password: {{ .Values.mongodb.password }}
  database: {{ .Values.mongodb.database }}

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
type: Opaque
stringData:
  rootPassword: {{ .Values.mysqldb.rootPassword }}
  username: {{ .Values.mysqldb.username }}
  password: {{ .Values.mysqldb.password }}
  database: {{ .Values.mysqldb.database }}
